apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: ghcr.io/kvel12/shopping-cart-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: ghcr.io/kvel12/shopping-cart-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
      - name: error-pages
        image: tarampampam/error-pages:latest
        ports:
        - containerPort: 8080
        env:
        - name: ERROR_CODE
          value: "410" 
        - name: TEMPLATE_NAME
          value: "lost-in-space" 
        - name: SHOW_DETAILS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  type: NodePort
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
spec:
  selector:
    app: error-pages
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080 # Puerto del contenedor
      nodePort: 30081  # Puerto expuesto en el nodo para el acceso externo
  type: NodePort
